name: CI-Harbor

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  build-and-push:
    runs-on: self-hosted
    needs: build
    if: ${{ needs.build.outputs.quality_gate_status == 'PASSED' }} # Quality Gate 실패 시 실행 안 함

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Login to Harbor (Secure)
        run: |
          echo "${{ secrets.HARBOR_PASSWORD }}" | docker login https://192.168.2.76:443 -u ${{ secrets.HARBOR_USERNAME }} --password-stdin

      - name: Build and push Docker images
        run: |
          BUILD_NUMBER=${{ github.run_number }} # GitHub Actions 빌드 번호
          docker build -t 192.168.2.76:443/hama/hama-frontend:$BUILD_NUMBER .
          docker push 192.168.2.76:443/hama/hama-frontend:$BUILD_NUMBER
