name: Build and Push Docker Image to Harbor

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Set Docker daemon to allow insecure registry (Harbor without HTTPS)
      - name: Configure Docker to allow insecure registry
        run: |
          echo '{ "insecure-registries":["192.168.2.76:443"] }' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker

      # Ping Harbor server to check connectivity
      - name: Ping Harbor server
        run: ping -c 4 192.168.2.76

      # Log in to Harbor
      - name: Log in to Harbor
        run: |
          echo "${{ secrets.HARBOR_PASSWORD }}" | docker login http://192.168.2.76:443 -u "${{ secrets.HARBOR_USERNAME }}" --password-stdin

      # Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build -t 192.168.2.76:443/your-repository/your-image:latest .
          docker push 192.168.2.76:443/your-repository/your-image:latest
